FROM python:3.13-slim

WORKDIR /app

COPY requirements.txt requirements.txt

# this is to fix the error where it fails to build 'psycopg2' package when installing from requirements.txt
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]